### DISCUSSION TITLE
Provide a way to reference instances of the same object (Instance Groups)

### DISCUSSION THREAD

**Discussion by tristanbob** [4ian/GDevelop#2748] [Enhancement ideas (and their technical discussions)]
Is it correct to say that one weakness in GDevelop is that it is impossible to control interaction between instances of the same object?  When using ForEach, you can only reference the instance that is currently in the loop.  Can we think of a way to allow referencing other instances of the same object?

I ran into this problem with my Physics Chains extension.  I had to use two different objects that connected ObjectA to ObjectB.   I could not make an event that connected InstanceA to InstanceB.

What if we make a new Action that saves the currently picked instances with a Name that can be used later?  (This Name functions as a temporary Instance Group.)

```
<previous code assigns an "ID" object variable to every instance>

EVENT:
 - Condition:  MyObject.Variable(ID)=1
 - Action:  Picked instances of "MyObject" can be referenced as "FirstInstance"
  
EVENT:
 - Condition:  MyObject.Variable(ID)=2
 - Action:  Picked instances of "MyObject" can be referenced as "SecondInstance"

EVENT:
 - Condition:  Distance between "FirstInstance" and "SecondInstance" is less than 10 pixels
 - Action:  Put "FirstInstance" around "SecondInstance" at a distance of 10 pixels and angle 0.
```

Would this idea be helpful?  Is there a better way to provide this functionality?
